fresh_every_day/apps/fresh_cart/urls.py
from django.conf.urls import url,include
from .views import *
urlpatterns = [
    url(r'^add$',CartAddView.as_view(),name='add'), #添加购物车
    url(r'^$',CartInfoView.as_view(),name='show'), #购物车页面显示
    url(r'^update$',CartUpdateView.as_view(),name='update'), #购物车记录更新
    url(r'^delete$',CartDeleteView.as_view(),name='delete'),#购物车记录删除

]

fresh_every_day/apps/fresh_goods/urls.py
from django.conf.urls import url
from .views import *
urlpatterns=[
    url(r'^home$',HomeView.as_view(),name='home'),
    url(r'^goods/(?P<goods_id>\d+)$',DetailView.as_view(),name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$',ListView.as_view(),name='list')
]

fresh_every_day/apps/fresh_order/urls.py
from django.conf.urls import url,include
from .views import *
urlpatterns = [
    url(r'^place$',OrderPlaceView.as_view(),name='place'),#提交订单页面
    url(r'^commit$',OrderCommitView.as_view(),name='commit'), #订单创建
    url('^pay$',OrderPayView.as_view(),name='pay'),#订单支付
    url(r'^check$',OrderCheckView.as_view(),name='check'), #检验订单是否支付
]

fresh_every_day/apps/fresh_user/urls.py
from django.contrib.auth.decorators import login_required
from django.conf.urls import url,include
from django.urls import path
from .views import  *
"""
login_required() --django内置装饰器
判断用户是否登陆
登录--执行括号中的视图函数
未登录--重定向到含有next的页面 如 ：http://127.0.0.1:8000/accounts/login/?next=/user/
"""
urlpatterns=[
# url(r'^',send), #测试邮件发送
    url(r'^register$',Register.as_view(),name='register'), #注册
    url(r"^active/(?P<token>.*)$", Active.as_view(),name='active'), #激活邮件
    url(r'^login$',Login.as_view(),name='login'), #登录
    url(r'^logout$',LoginoutView.as_view(),name='logout'),#退出登录
    path('sms_send/<phone>/', sms_send, name="sms_send"),#短信发送
    path('sms_check/',sms_check, name="sms_check"),#短信验证
    path('img_refresh/',img_refresh,name='img_refresh'),#图形验证码刷新
    path('img_check/',img_check,name='img_check'),#图形验证码验证

    # url(r'^$',login_required(UserInfoView.as_view()),name='user'), #用户中心--信息页
    # url(r'^order$',login_required(UserOrderView.as_view()),name='order'), #用户中心--订单页
    # url(r'^address$',login_required(AddressView.as_view()),name='address') #用户中心--地址页
    url(r'^$',UserInfoView.as_view(),name='user'), #用户中心--信息页
    url(r'^order/(?P<page>\d+)$',UserOrderView.as_view(),name='order'), #用户中心--订单页
    url(r'^address$',AddressView.as_view(),name='address') #用户中心--地址页
]

fresh_every_day/fresh_every_day/fresh_every_day/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^user/',include(('fresh_user.urls','fresh_user'),namespace='user')), #用户模块
    url(r'^cart/',include(('fresh_cart.urls','fresh_cart'),namespace='cart')), #购物车模块
    url(r'^order/',include(('fresh_order.urls','fresh_order'),namespace='order')), #订单模块
    url(r'^',include(('fresh_goods.urls','fresh_goods'),namespace='goods')),#商品模块
    path('captcha',include('captcha.urls')), #图形验证码
    url(r'^tinymce/',include('tinymce.urls')), #富文本编辑器
    url(r'^search',include('haystack.urls')) #全文检索框架
]

fresh_every_day/fresh_every_day/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^user/',include(('fresh_user.urls','fresh_user'),namespace='user')), #用户模块
    url(r'^cart/',include(('fresh_cart.urls','fresh_cart'),namespace='cart')), #购物车模块
    url(r'^order/',include(('fresh_order.urls','fresh_order'),namespace='order')), #订单模块
    url(r'^',include(('fresh_goods.urls','fresh_goods'),namespace='goods')),#商品模块
    path('captcha',include('captcha.urls')), #图形验证码
    url(r'^tinymce/',include('tinymce.urls')), #富文本编辑器
    url(r'^search',include('haystack.urls')) #全文检索框架
]

fresh_every_day/templates/base.html
{#首页、注册、登录#}
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	<title>{% block title %}

	{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{#网页顶部文件块#}
{% block topfiles %}

{% endblock %}
{#网页顶部欢迎信息块#}
{% block header_con %}
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到海马生鲜!</div>
			<div class="fr">
                {% if user.is_authenticated %}
				<div class="login_btn fl">
					欢迎您：<em>{{ user.username }}</em>
                    <span>|</span>
					<a href="{% url 'user:logout' %}">退出</a>
				</div>
                {% else %}
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
                {% endif %}
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'cart:show' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' 1 %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{#网页顶部搜索块#}
{% block search_con %}
<div class="search_bar clearfix">
		<a href="{% url 'goods:home' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
            <form action="/search" method="get">
                <input type="text" class="input_text fl" name="q" placeholder="搜索商品">
                <input type="submit" class="input_btn fr" name="" value="搜索">
            </form>
		</div>
		<div class="guest_cart fr">
			<a href="{% url 'cart:show' %}" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock %}
{#网页主体内容#}
{% block body %}

{% endblock %}
{#网页底部#}
<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{#网页底部html块#}
{% block bottom %}

{% endblock %}
{#网页底部文件导入#}
{% block bottomfiles %}

{% endblock %}

fresh_every_day/templates/base_detail_list.html
{#详情页、列表页#}
{% extends 'base.html' %}
{% block body %}
<div class="navbar_con">
		<div class="navbar clearfix">
			<div class="subnav_con fl">
				<h1>全部商品分类</h1>
				<span></span>
				<ul class="subnav">
                    {% for type in types %}
                        <li><a href="{% url 'goods:list' type.id 1 %}" class="{{ type.logo }}">{{ type.name }}</a></li>
                    {% endfor %}
				</ul>
			</div>
			<ul class="navlist fl">
				<li><a href="">首页</a></li>
				<li class="interval">|</li>
				<li><a href="">手机生鲜</a></li>
				<li class="interval">|</li>
				<li><a href="">抽奖</a></li>
			</ul>
		</div>
	</div>
{#    详情页、列表页主体内容块#}
    {% block main_content %}
    
    {% endblock %}
{% endblock %}

fresh_every_day/templates/base_no_cart.html
{#购物车、提交订单、用户中心继承#}
{% extends 'base.html' %}
{% load static %}
{% block search_con %}
	<div class="search_bar clearfix">
		<a href="{% url 'goods:home' %}" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="sub_page_name fl">|&nbsp;&nbsp;&nbsp;&nbsp;{% block page_title %}
		
		{% endblock %}</div>
		<div class="search_con fr">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
	</div>
{% endblock %}

fresh_every_day/templates/cart.html
{% extends 'base_no_cart.html' %}
{% load static %}
{% block title %}
天天生鲜-购物车
{% endblock %}
{% block page_title %}
购物车
{% endblock %}
{% block body %}
	<div class="total_count">全部商品<em>{{ total_count }}</em>件</div>
	<ul class="cart_list_th clearfix">
		<li class="col01">商品名称</li>
		<li class="col02">商品单位</li>
		<li class="col03">商品价格</li>
		<li class="col04">数量</li>
		<li class="col05">小计</li>
		<li class="col06">操作</li>
	</ul>
    <form method="post" action="{% url 'order:place' %}">
    {% for sku in skus %}
	<ul class="cart_list_td clearfix">
		<li class="col01"><input type="checkbox" name="sku_ids" value="{{ sku.id }}" checked></li>
		<li class="col02"><img src="{{ sku.image.url }}"></li>
		<li class="col03">{{ sku.name }}<br><em>{{ sku.price }}元/{{ sku.unite }}</em></li>
		<li class="col04">{{ sku.unite }}</li>
		<li class="col05">{{ sku.price }}</li>
		<li class="col06">
			<div class="num_add">
				<a href="javascript:;" class="add fl">+</a>
				<input type="text" sku_id="{{ sku.id }}" class="num_show fl" value="{{ sku.count }}">
				<a href="javascript:;" class="minus fl">-</a>	
			</div>
		</li>
		<li class="col07">{{ sku.amount }}</li>
		<li class="col08"><a href="javascript:;">删除</a></li>
	</ul>
    {% endfor %}
    {% csrf_token %}
	<ul class="settlements">
		<li class="col01"><input type="checkbox" name="" checked=""></li>
		<li class="col02">全选</li>
		<li class="col03">合计(不含运费)：<span>¥</span><em>{{ total_price }}</em><br>共计<b>{{ total_count }}</b>件商品</li>
		<li class="col04"><input type="submit" value="去结算"></li>
	</ul>
    </form>
{% endblock %}

{% block bottomfiles %}
    <script src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
    <script>
        //计算被选中的商品总价和总数量
        function update_page_info(){
            //获取所有被选中的商品的checkbox
            //获取所有被选中的商品所在的ul元素
            total_count=0;
            total_price=0;
            $('.cart_list_td').find(':checked').parents('ul').each(function(){
                //获取商品的数目和小计
                count=$(this).find('.num_show').val();
                amount=$(this).children('.col07').text();
                //累加计算商品的总件数和总价格
                count=parseInt(count);
                amount=parseFloat(amount);
                total_count+=count;
                total_price+=amount
            });
            //设置被选中的商品的总件数和总价格
            $('.settlements').find('em').text(total_price.toFixed(2));
            $('.settlements').find('b').text(total_count)
        }
        //计算商品的小计
        //通过传递ul标签来计算小计
        function update_goods_amount(sku_ul){
            //获取商品的价格和数量
            count=sku_ul.find('.num_show').val();
            price=sku_ul.children('.col05').text();
            //计算商品的小计
            amount=parseInt(count)*parseFloat(price);
            //设置商品的小计
            sku_ul.children('.col07').text(amount.toFixed(2)+'元')
        }
        //商品全选和全不选
        $('.settlements').find(':checkbox').change(function () {
            //获取全选的checkbox的选中状态
            is_checked=$(this).prop('checked');
            //遍历商品的对应的checkbox，设置这些checkbox的选中状态和全选的checkbox保持一致
            $('.cart_list_td').find(':checkbox').each(function () {
                $(this).prop('checked',is_checked)

            });
            //更新页面的信息
            update_page_info()
        });
        //商品对应的checkbox发生改变时，设置全选的checkbox状态
        $('.cart_list_td').find(':checked').change(function () {
            //获取页面上所有的商品数目
            all_len=$('.cart_list_td').length;
            //获取页面上被选中的商品数目
            checked_len=$('.cart_list_td').find(':checked').length;
            //进行判断
            //如果被选取的商品数目小于页面商品数目  全选框为False
            //如果被选取的商品数目小于页面商品数目  全选框为True
            if (checked_len < all_len){
                $('.settlements').find(':checked').prop('checked',false)
            }
            else{
                $('.settlements').find(':checked').prop('checked',true)
            }
            //更新页面信息
            update_page_info()
        });

        //更新购物车中商品的数量
        error_update=false; //判断是否发送成功 对页面信息进行更新
        total=0;
        function update_remote_cart_info(sku_id,count){
             csrf=$('input[name="csrfmiddlewaretoken"]').val();
            //组织参数
             params={'sku_id':sku_id,'count':count,'csrfmiddlewaretoken':csrf};
             //发起之前设置ajax请求为同步
             $.ajaxSettings.async=false;
             $.post('/cart/update',params,function (data) {
                if (data.res == 5){
                    //更新成功
                    error_update=false;
                    total=data.total_count
                }
                else{
                    //更新失败
                    error_update=true;
                    alert(data.errmsg)
                }
            });
             //设置ajax请求为异步
            $.ajaxSettings.async=true;
        }
        //购物车商品数目的增加
        $('.add').click(function () {
            //获取商品的id和商品的数量
            sku_id = $(this).next().attr('sku_id');
            count = $(this).next().val();
            //csrf = $('input[name="csrfmiddlewaretoken"]').val();
            //校验参数
            count = parseInt(count) + 1;
            //更新购物车中的记录
            update_remote_cart_info(sku_id,count);
                //判断是否更新成功
                if (error_update == false) {
                    //重新设置商品的数目
                    $(this).next().val(count);
                    //计算商品的小计
                    update_goods_amount($(this).parents('ul'));
                    //获取商品对应的checkbox选中状态，如果被选中，更新页面信息
                    is_checked = $(this).parents('ul').find(':checkbox').prop('checked');
                    if (is_checked) {
                        //更新页面信息
                        update_page_info()
                    }
                    //更新页面上购物车商品的总件数
                    $('.total_count').children('em').text(total);
                }
            });

        //购物车商品数目的减少
        $('.minus').click(function () {
            //获取商品的id和商品的数量
            sku_id = $(this).prev().attr('sku_id');
            count = $(this).prev().val();
            //csrf=$('input[name="csrfmiddlewarewoken"]').val();
            //组织参数
            count = parseInt(count) - 1;
            //加入判断  不能小于1
            if (count <= 0) {
                return
            }
            //更新购物车的记录
            update_remote_cart_info(sku_id, count);
                //判断是否更新成功
            if (error_update == false) {
                //重新设置商品的数目
                $(this).prev().val(count);
                //计算商品的小计
                update_goods_amount($(this).parents('ul'));
                //获取商品对应的checkbox选中状态，如果被选中，更新页面信息
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked');
                if (is_checked) {
                    //更新页面信息
                    update_page_info()
                }
                //更新页面上购物车商品的总件数
                $('.total_count').children('em').text(total)
            }
        });
        //记录用户输入之前商品的数量
        pre_count = 0;
        $('.num_show').focus(function () {
            pre_count = $(this).val()
        });
        //手动输入商品的数量
        //购物车商品数目的减少
        $('.num_show').blur(function () {
            //获取商品的id和商品的数量
            sku_id = $(this).attr('sku_id');
            count = $(this).val();
            //校验参数
            if (isNaN(count) || count.trim().length == 0 || parseInt(count) <= 0) {
                //设置商品的数目为用户输入之前的数目
                $(this).val(pre_count);
                return
            }
            count = parseInt(count);
            //更新购物车的记录
            update_remote_cart_info(sku_id, count);
            if (error_update == false) {
                //重新设置商品的数目
                $(this).prev().val(count);
                //计算商品的小计
                update_goods_amount($(this).parents('ul'));
                //获取商品对应的checkbox选中状态，如果被选中，更新页面信息
                is_checked = $(this).parents('ul').find(':checkbox').prop('checked');
                if (is_checked) {
                    //更新页面信息
                    update_page_info()
                }
                    //更新页面上购物车商品的总件数
                $('.total_count').children('em').text(total)
            } else {
                    //设置商品的数目为用户输入之前的数目
                $(this).val(pre_count);
            }
        });

        //删除购物车中记录
        $('.cart_list_td').children('.col08').children('a').click(function () {
            //获取对应的商品id
            sku_id=$(this).parents('ul').find('.num_show').attr('sku_id');
            csrf=$('input[name="csrfmiddlewarewoken"]').val();
            //组织参数
            params={'sku_id':sku_id,'csrfmiddlewaretoken':csrf};
            //获取商品所在的ul元素
            sku_ul=$(this).parents('ul');
            //发起ajax post请求 方位/cart/delete 传递参数 sku_id
            $.post('/cart/delete',params,function (data) {
                if(data.res==3){
                    //删除成功，移除页面上商品所在的ul元素
                    //remove() 移除元素本身及所包含的子元素
                    //empty() 只移除子元素不包括它本身
                    sku_ul.remove();
                    //获取sku_ul中商品的选中状态
                    is_checked=sku_ul.find(':checkbox').prop('checked');
                    if (is_checked){
                        //更新页面信息
                        update_page_info()
                    }
                    //重新设置页面上购物车中商品的总件数
                    $('.total_count').children('em').text(data.total_count)
                }
                else{
                    alert(errmsg)
                }
            })
        })

    </script>
{% endblock %}

fresh_every_day/templates/place_order.html
{% extends 'base_no_cart.html' %}
{% load static %}
{% block title %}
天天生鲜-提交订单
{% endblock %}
{% block body %}
	<h3 class="common_title">确认收货地址</h3>
	<div class="common_list_con clearfix">
		<dl>
			<dt>寄送到：</dt>
            {% for addr in addrs %}
			<dd><input type="radio" name="addr_id"  value="{{ addr.id }}" {% if addr.is_default %}checked{% endif %}
			 checked="">{{ addr.addr }} {{ addr.receiver }} {{ addr.phone }}</dd>
            {% endfor %}
		</dl>
		<a href="{% url 'user:address' %}" class="edit_site">编辑收货地址</a>

	</div>
	
	<h3 class="common_title">支付方式</h3>	
	<div class="common_list_con clearfix">
		<div class="pay_style_con clearfix">
			<input type="radio" name="pay_style" checked value="1">
			<label class="cash">货到付款</label>
			<input type="radio" name="pay_style" value="2">
			<label class="weixin">微信支付</label>
			<input type="radio" name="pay_style" value="3">
			<label class="zhifubao"></label>
			<input type="radio" name="pay_style" value="4">
			<label class="bank">银行卡支付</label>
		</div>
	</div>

	<h3 class="common_title">商品列表</h3>
	
	<div class="common_list_con clearfix">
		<ul class="goods_list_th clearfix">
			<li class="col01">商品名称</li>
			<li class="col02">商品单位</li>
			<li class="col03">商品价格</li>
			<li class="col04">数量</li>
			<li class="col05">小计</li>		
		</ul>
        {% for sku in skus %}
		<ul class="goods_list_td clearfix">
			<li class="col01">{{ forloop.counter }}</li>
			<li class="col02"><img src="{{ sku.image.url }}"></li>
			<li class="col03">{{ sku.name }}</li>
			<li class="col04">{{ sku.unite }}</li>
			<li class="col05">{{ sku.price }}元</li>
			<li class="col06">{{ sku.count }}</li>
			<li class="col07">{{ sku.amount }}元</li>
		</ul>
        {% endfor %}
	</div>

	<h3 class="common_title">总金额结算</h3>

	<div class="common_list_con clearfix">
		<div class="settle_con">
			<div class="total_goods_count">共<em>{{ total_conut }}</em>件商品，总金额<b>{{ total_price }}元</b></div>
			<div class="transit">运费：<b>{{ transit_price }}元</b></div>
			<div class="total_pay">实付款：<b>{{ total_bay }}元</b></div>
		</div>
	</div>

	<div class="order_submit clearfix">
		<a href="javascript:;" sku_ids="{{ sku_ids }}" id="order_btn">提交订单</a>
	</div>	


    {% block bottom %}
	<div class="popup_con">
		<div class="popup">
			<p>订单提交成功！</p>
		</div>
		
		<div class="mask"></div>
	</div>
        {% endblock %}
    {% block bottomfiles %}
	<script type="text/javascript" src="{% static 'js/jquery-1.12.4.min.js' %}"></script>
	<script type="text/javascript">
		$('#order_btn').click(function() {
		    //获取用户选择的地址id、支付方式、要购买的商品id字符串
            addr_id=$('input[name="addr_id"]:checked').val();
            pay_method=$('input[name="pay_style"]:checked').val();
            sku_ids=$(this).attr('sku_ids');
            csrf=$('input[name="csrfmiddlewaretoken"]').val();
            //alert(addr_id+":",pay_method+":",sku_ids+":");
            //组织参数
            params={"addr_id":addr_id,"pay_method":pay_method,"sku_ids":sku_ids};
            //发起ajax post请求 访问/order/commit,传递的参数:addr_id,pay_method,sku_ids
            $.post('/order/commit',params,function (data) {
                if (data.res==5){
                    //创建成功
                    localStorage.setItem('order_finish',2);
                    $('.popup_con').fadeIn('fast',function () {
                        setTimeout(function () {
                            $('.popup_con').fadeOut('fast',function () {
                                window.location.href='{% url "user:order" 1 %}';
                            });
                        },3000)
                    })
                }
                else{
                    alert(data.errmsg)
                }
            });
		{#	localStorage.setItem('order_finish',2);#}
        {##}
		{#	$('.popup_con').fadeIn('fast', function() {#}
        {##}
		{#		setTimeout(function(){#}
		{#			$('.popup_con').fadeOut('fast',function(){#}
		{#				window.location.href = 'index.html';#}
		{#			});	#}
		{#		},3000)#}
		{#		#}
		{#	});#}
		})
	</script>
        {% endblock %}
{% endblock %}

fresh_every_day/templates/static_base.html
{#首页、注册、登录#}
{% load static %}
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">

	<title>{% block title %}

	{% endblock %}</title>
	<link rel="stylesheet" type="text/css" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{#网页顶部文件块#}
{% block topfiles %}

{% endblock %}
{#网页顶部欢迎信息块#}
{% block header_con %}
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎来到海马生鲜!</div>
			<div class="fr">
				<div class="login_btn fl">
					<a href="{% url 'user:login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'user:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'user:user' %}">用户中心</a>
					<span>|</span>
					<a href="cart.html">我的购物车</a>
					<span>|</span>
					<a href="{% url 'user:order' %}">我的订单</a>
				</div>
			</div>
		</div>
	</div>
{% endblock %}
{#网页顶部搜索块#}
{% block search_con %}
<div class="search_bar clearfix">
		<a href="index.html" class="logo fl"><img src="{% static 'images/logo.png' %}"></a>
		<div class="search_con fl">
			<input type="text" class="input_text fl" name="" placeholder="搜索商品">
			<input type="button" class="input_btn fr" name="" value="搜索">
		</div>
		<div class="guest_cart fr">
			<a href="#" class="cart_name fl">我的购物车</a>
			<div class="goods_count fl" id="show_count">{{ cart_count }}</div>
		</div>
	</div>
{% endblock %}
{#网页主体内容#}
{% block body %}

{% endblock %}
{#网页底部#}
<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2016 北京天天生鲜信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-****888    京ICP备*******8号</p>
	</div>
{#网页底部html块#}
{% block bottom %}

{% endblock %}
{#网页底部文件导入#}
{% block bottomfiles %}

{% endblock %}

fresh_every_day/templates/user_center_info.html
{% extends 'base_user_center.html' %}
{% load static %}
{% block right_content %}
		<div class="right_content clearfix">
				<div class="info_con clearfix">
				<h3 class="common_title2">基本信息</h3>
						<ul class="user_info_list">
							<li><span>用户名：</span>{{ user.username }}</li>
                            {% if address %}
							<li><span>联系方式：</span>{{ address.phone }}</li>
							<li><span>联系地址：</span>{{ address.addr }}</li>
                            {% else %}
                                <li><span>联系方式：</span>无默认联系方式</li>
							    <li><span>联系地址：</span>无默认收货地址</li>
                            {% endif %}
						</ul>
				</div>
				<h3 class="common_title2">最近浏览</h3>
				<div class="has_view_list">
					<ul class="goods_type_list clearfix">
                        {% for goods in goods_li %}
                        <li>
                            <a href="detail.html"><img src="{{ goods.image.url }}"></a>
                            <h4><a href="detail.html">{{ goods.name }}</a></h4>
                            <div class="operate">
                                <span class="prize">{{ goods.price }}</span>
                                <span class="unit">{{ goods.price }}/{{ goods.unite }}</span>
                                <a href="#" class="add_goods" title="加入购物车"></a>
                            </div>
                        </li>
                            {% empty %}
                                无历史浏览记录
                        {% endfor %}
			        </ul>
		        </div>
		</div>

{% endblock %}