fresh_every_day/apps/fresh_goods/urls.py
from django.conf.urls import url
from .views import *
urlpatterns=[
    url(r'^home$',HomeView.as_view(),name='home'),
    url(r'^goods/(?P<goods_id>\d+)$',DetailView.as_view(),name='detail'),
    url(r'^list/(?P<type_id>\d+)/(?P<page>\d+)$',ListView.as_view(),name='list')
]

fresh_every_day/fresh_every_day/fresh_every_day/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^user/',include(('fresh_user.urls','fresh_user'),namespace='user')), #用户模块
    url(r'^cart/',include(('fresh_cart.urls','fresh_cart'),namespace='cart')), #购物车模块
    url(r'^order/',include(('fresh_order.urls','fresh_order'),namespace='order')), #订单模块
    url(r'^',include(('fresh_goods.urls','fresh_goods'),namespace='goods')),#商品模块
    path('captcha',include('captcha.urls')), #图形验证码
    url(r'^tinymce/',include('tinymce.urls')), #富文本编辑器
    url(r'^search',include('haystack.urls')) #全文检索框架
]

fresh_every_day/fresh_every_day/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url,include
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^user/',include(('fresh_user.urls','fresh_user'),namespace='user')), #用户模块
    url(r'^cart/',include(('fresh_cart.urls','fresh_cart'),namespace='cart')), #购物车模块
    url(r'^order/',include(('fresh_order.urls','fresh_order'),namespace='order')), #订单模块
    url(r'^',include(('fresh_goods.urls','fresh_goods'),namespace='goods')),#商品模块
    path('captcha',include('captcha.urls')), #图形验证码
    url(r'^tinymce/',include('tinymce.urls')), #富文本编辑器
    url(r'^search',include('haystack.urls')) #全文检索框架
]

fresh_every_day/templates/search/search.html
{% extends 'base_detail_list.html' %}
{% load static %}
{% block title %}
天天生鲜-商品搜索结果列表
{% endblock %}
{% block main_content %}

	<div class="breadcrumb">
		<a href="#">{{ query }}</a>
		<span>></span>
		<a href="#">搜索结果如下：</a>
	</div>

	<div class="main_wrap clearfix">
			<ul class="goods_type_list clearfix">
                {% for item in page %}
				<li>
					<a href="{% url 'goods:detail' item.object.id %}"><img src="{{ item.object.image.url }}"></a>
					<h4><a href="{% url 'goods:detail' item.object.id %}">{{ item.object.name }}</a></h4>
					<div class="operate">
						<span class="prize">￥{{ item.object.price }}</span>
						<span class="unit">{{ item.object.price }}/{{ item.object.unite }}</span>
						<a href="#" class="add_goods" title="加入购物车"></a>
					</div>
				</li>
                {% endfor %}
			</ul>
			<div class="pagenation">
{#            has_previous判断是否有上一页#}
{#                previous_page_number返回上一页的页码#}
                {% if page.has_previous %}
                    <a href="/search?q={{ query }}&page={{ page.previous_page_number }}"><上一页</a>
                {% endif %}
{#            page_range返回paginator对象的页码列表#}
                {% for pindex in paginator.page_range %}
                    {% if pindex == page.number %}
                        <a href="/search?q={{ query }}&page={{ pindex }}" class="active">{{ pindex }}</a>
                    {% else %}
                        <a href="/search?q={{ query }}&page={{ pindex }}">{{ pindex }}</a>
                    {% endif %}
                {% endfor %}
{#            has_next判断是否有下一页#}
            {% if page.has_next %}
                <a href="/search?q={{ query }}&page={{ page.next_page_number }}">下一页></a>
            {% endif %}
			</div>
		</div>
{% endblock %}